# Site settings
title: Jason Steinshouer
description: >
 Personal notes on web development and technology. If it helps someone else, thats nice too.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonsteinshouer.com" # the base hostname & protocol for your site

author:
  fullname: Jason Steinshouer
  #googleplus: https://www.google.com/+MotaquillahMaddane
  github: jsteinshouer
  twitter: jdsteinshouer
  disqus: jasonsteinshouer

google_analytics: 'UA-80138644-1'

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
