name: Jason Steinshouer
description: web development and technology
meta_description: "blog on web development and technology"

markdown: kramdown
highlighter: none
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jasonsteinshouer.com'
google_analytics: 'UA-80138644-1'
gems: [jekyll-paginate]

author:
  fullname: 'Jason Steinshouer'
  github: jsteinshouer
  twitter: jdsteinshouer
  disqus: jasonsteinshouer
  avatar: 'https://avatars0.githubusercontent.com/u/2914865'

# Details for the RSS feed generator
url:            'http://jasonsteinshouer.com'


exclude: ["README.md", "docker-compose.yml","LICENSE.txt"]